# Basic server properties
server:
  port: ${ADMIN_PORT:8777}

# Basic spring properties
spring:
  # Application
  application:
    name: ${ADMIN_APPLICATION_NAME:admin-service}
  boot:
    admin:
      context-path: /admin

# Basic actuator properties
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:*}
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_SHOW_DETAILS:always}